package net.thumbtack.onlineshop.error;

public enum UserErrorCode {
    INVALID_FIRST_NAME,
    INVALID_LAST_NAME,
    INVALID_PATRONYMIC_NAME,
    INVALID_POSITION,
    INVALID_LOGIN,
    INVALID_PASSWORD,
    ACCESS_DENIED,
    WRONG_LOGIN_OR_PASSWORD,
    INVALID_SESSION,
    WRONG_CATEGORY_NAME,
    WRONG_GATEGORY_ID,
    WRONG_CANT_EDIT_PARENT_GATEGORY,
    CLIENTS_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    WRONG_ERROR_WITH_PRODUCT,
    WRONG_PRODUCT_ID,
    WRONG_ORDER_NAME,
    WRONG_EMAIL,
    WRONG_ADDRESS,
    WRONG_PHONE,
    WRONG_DEPOSIT,
    WRONG_ClIENT_DEPOSIT_TO_LOW,
    WRONG_PRODUCT_COUNT,
    WRONG_DATE
}
